package com.mathhelper.mathhelperserver.forms.task

import com.mathhelper.mathhelperserver.constants.Constants
import com.mathhelper.mathhelperserver.datatables.tasks.GoalType
import com.mathhelper.mathhelperserver.forms.rule_pack.RulePackLinkForm
import org.hibernate.annotations.Type
import java.sql.Timestamp
import javax.persistence.Column
import javax.validation.constraints.NotBlank
import javax.validation.constraints.Pattern
import javax.validation.constraints.Size

data class TaskForm(
    @field:NotBlank
    @field:Size(min = Constants.MIN_LENGTH, max = Constants.STRING_LENGTH_LONG)
    @field:Pattern(regexp = Constants.ALL_EXCEPT_AT_SYMBOL)
    var namespaceCode: String,

    var code: String? = null,

    var version: Int? = null,

    var taskCreationType: String? = "",

    @field:Size(min = Constants.MIN_LENGTH, max = Constants.STRING_LENGTH_LONG)
    var nameEn: String? = null,

    @field:Size(min = Constants.MIN_LENGTH, max = Constants.STRING_LENGTH_LONG)
    var nameRu: String? = null,

    var descriptionShortEn: String? = "",

    var descriptionShortRu: String? = "",

    var descriptionEn: String? = "",

    var descriptionRu: String? = "",

    var subjectType: String? = "",

    var originalExpressionStructureString: String = "",

    var originalExpressionTex: String = "",

    var originalExpressionPlainText: String = "",

    var originalExpression: MutableMap<String, *>? = null,

    var goalType: String = GoalType.CUSTOM.code,

    var goalExpressionStructureString: String? = null,

    var goalExpressionTex: String? = null,

    var goalExpressionPlainText: String? = null,

    var goalExpression: MutableMap<String, *>? = null,

    var goalPattern: String? = null,

    var otherGoalData: MutableMap<String, *>? = null,

    var rulePacks: ArrayList<RulePackLinkForm>? = null,

    var rules: ArrayList<*>? = null,

    var tags: ArrayList<String>? = null,

    var stepsNumber: Int? = null,

    var time: Int? = null,

    var difficulty: Double,

    var solution: MutableMap<String, *>? = null,

    var solutionsStepsTree: MutableMap<String, *>? = null,

    var hints: MutableMap<String, *>? = null,

    var otherCheckSolutionData: MutableMap<String, *>? = null,

    var countOfAutoGeneratedTasks: Int? = 0,

    var otherAutoGenerationData: MutableMap<String, *>? = null,

    var interestingFacts: MutableMap<String, *>? = null,

    var otherAwardData: MutableMap<String, *>? = null,

    var nextRecommendedTasks: MutableMap<String, *>? = null,

    var otherData: MutableMap<String, *>? = null
)
